### PR TITLE
added es-419 for convert_speed

### PR DESCRIPTION
**Pull request by ShodytheWolf**
what the title says

### CODE REVIEW

**Comment by JDJGInc** [comment]
Alright.
Cool

**Comment by ShodytheWolf** [comment]
O Orang

**Comment by Hadock-is-ok** [comment]
lgtm, other than having 2 of the same thing.

**Comment by ShodytheWolf** [comment]
It's more of neutral spanish, it should be readable by both, latin americans and Spain Spanish

**Comment by Hadock-is-ok** [comment]
lgtm

**Pull request merged**
