### PR TITLE
Rearrange and add more info for ticket closing

### PR DESCRIPTION
**Pull request by thatrandomperson5**
Added message saying "ticket was successfully closed"

### CODE REVIEW

**Comment by JDJGInc** [comment]
Your ticket in the else should be the user's ticket to show it's a support thread.

**Comment by thatrandomperson5** [comment]
add `thread=remote`?

**Comment by JDJGInc** [comment]
> add `thread=remote`?

For what?

**Comment by JDJGInc** [comment]
> Contributor

It seems to send to the right place

Also if someone runs te*close in the support channel then there are no issues.

**Comment by JDJGInc** [comment]
https://github.com/JDsProjects/JDBot/blob/178d99a22859512ee151bc88d6712450b950316a/cogs/tickets.py#L213

There's also a bug with this.

**Comment by JDJGInc** [comment]
> > if message.author == author and not self.support_role not in message.author.roles
> 
> `Blank not in blank` is improper, use `not blank in blank`

You could probaly solve this if you wish, but I can solve it too, after I look around.

**Comment by thatrandomperson5** [comment]
So what did you want me to add?

**Comment by JDJGInc** [comment]
> So what did you want me to add?

You can fix the check if you want, but i could also solve this easily as well.

**Comment by thatrandomperson5** [comment]
Done and remember to squash

**Pull request merged**
