### PR TITLE
More accurate Chinese(Simplified) translation

### PR DESCRIPTION
**Pull request by 8192Bit**

### CODE REVIEW

**Comment by JDJGInc** [comment]
If you want to talk to me about the pr
Add me on discord with ``jdjg``

**Comment by JDJGInc** [comment]
https://discord.com/users/168422909482762240

**Review by sus2790 — APPROVED** [review]
LGTM

**Comment by JDJGInc** [comment]
Cool, merged
Thank you

**Comment by JDJGInc** [comment]
I appreciate you making a translation fix, thank you.

**Pull request merged**
